# Generated by Django 4.1 on 2022-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
