# Generated by Django 4.1 on 2022-08-23 12:30

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[apps.users.validators.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
