# Generated by Django 4.1 on 2022-08-23 12:44

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='+375XXXXXXXXX', max_length=13, null=True, validators=[apps.users.validators.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
